apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.name }}
    tag: {{ .Values.metadata.imageTag}}
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.metadata.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
      tag: {{ .Values.metadata.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
        tag: {{ .Values.metadata.name }}
    spec:
      containers:
      - name: {{ .Values.metadata.name }}
        image: {{ .Values.metadata.repoName }}:{{ .Values.metadata.imageTag }}
        imagePullPolicy: {{ .Values.metadata.imagePullPolicy }}
        name: {{ .Values.metadata.name }}
        resources:
          requests:
            memory: {{ .Values.metadata.memoryRequest }}
            cpu: {{ .Values.metadata.cpuRequest }}