apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.name }}
    tag: {{ .Values.metadata.name }}
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
  - port: {{ .Values.metadata.ServicePort }}
    protocol: TCP
    targetPort: 8111
  selector:
    app: {{ .Values.metadata.name }}
    tag: {{ .Values.metadata.name }}
  type: {{ .Values.metadata.ServiceType }}
