name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    # required for buildx and multi platform build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - name: Set the value
        id: version_env
        run: |
          echo cat {{ $GITHUB_WORKSPACE}}/version.properties >> $GITHUB_ENV
      - name: Build container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.CR_USERNAME }}/nettracer-bpf:latest
            ${{ secrets.CR_USERNAME }}/nettracer-bpf:${{ env.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
