name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
    # required for buildx and multi platform build
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      # - uses: actions/checkout@v2
      # - name: Build container image
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     load: true
      #     tags: test:latest
      # - run: docker push ${{ env.IMAGE }}:${{ env.GIT_SHA }}
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=false" \