name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - name: Build container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: Build container image
      #   id: docker_build
      #   uses: docker/build-push-action@v1
      #   with:
      #     platforms: linux/amd64,linux/arm64
      #     context: .
      #     push: true
      #     tags: latest
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}