name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    # required for buildx and multi platform build
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Set the value
        id: version_env
        run: |
          awk -F 'version=' '{print $2}' $GITHUB_WORKSPACE/version.properties >> $GITHUB_ENV
      - name: Build container image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: |
            nettracer-bpf:latest
            nettracer-bpf:${{ env.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
