name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Print environment variables
        run: |
          echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
      - id: prep
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          echo ::set-output name=tags::ghcr.io/${{ CI_REPOSITORY_OWNER }}/${{ CI_REPOSITORY_NAME }}:${GITHUB_REF#refs/tags/v}
      - uses: docker/setup-qemu-action@master
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          platforms: all
      - id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true
      - uses: docker/login-action@v1
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!
      - uses: docker/build-push-action@v2-build-push
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/image/app/Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/386